### ISSUE TITLE
JD-800 Special Setup translates incorrectly to JD-990

### ISSUE THREAD

**Issue by gitl0ver** [sagamusix/JDTools#11]
I'd like to say thank you _so much_ for this tool. It's simple, flexible, and extremely helpful! I love it and use it constantly with my JD-990.

Now, something I noticed... on the latest published version (v0.16), when attempting to convert JD-800 Special Setup configurations to JD-990, all of the parameters within the chorus, delay, and reverb sections are ignored, leading the resulting converted Rhythm set to sound _especially_ different from the 800 in some cases. I'm happy to provide SysEx files/dumps to compare or whatever is necessary to research this issue should you be interested. I'd really, really appreciate it! Either way, thanks again for this awesome tool.

**Comment by sagamusix** [comment]
They are not ignored - they are simply not part of the special setup SysEx data. JD-990 special setups do contain the full effect section, but JD-800 special setups don't have that data - only full patches do.

**Comment by gitl0ver** [comment]
Agh! Wow...my bad!! No wonder...sorry, lol!
