### ISSUE TITLE
Support for conversion to ZC1 svz without models for MC-707/MC-101

### ISSUE THREAD

**Issue by viclabs** [sagamusix/JDTools#15]
Is it possible to allow conversion for raw zenology format with the JD-Multi as effects
Best effort WG would be great.
It would be great to be able to convert the zenology Model patches from the JP/JX/106/101 to raw ZC1 and JD-800 also.
Can I just set the modelID1 and modelID2 to 0?

Thanks for all your hard work.
I have transferred all my JD-800 and JD-990 patches to a new JD-08.  (purchased because of this software.

**Comment by sagamusix** [comment]
I don't think this is easily feasible , and certainly not something I have the motivation to spend weeks of reverse-engineering on, even if I had any ZenCore-based synths.
