### ISSUE TITLE
Linker error on Arch Linux

### ISSUE THREAD

**Issue by krenzlin** [sagamusix/JDTools#16]
First, thanks for your work. I stumbled across this project while trying to reverse engineer a JX-08 svd file. Wow, what a nightmare. At least reading about the "precomputed parameters" saved me from losing my mind. 

When I try to build the project on arch linux `ld` throws an error.
Please be aware that I am not a cmake user, so this might be an obvious user error.

To reproduce:

```bash
$ git clone https://github.com/sagamusix/JDTools
[...]
$ cd JDTools
$ cmake .
[...]
$ make
[...]
[100%] Linking CXX executable JDTools
/usr/bin/ld: cannot open output file JDTools: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/JDTools.dir/build.make:209: JDTools] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/JDTools.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

My guess is that the linker about there already being a directory called "JDTools". A name which it wants the executable to have.
On windows a "JDTools.exe" might not pose an issue. 

I can confirm the issue when I try to build it manually, 
```
$ g++ -std=c++20 JDTools/*.c JDTools/*.cpp -o JDTools
/usr/bin/ld: cannot open output file JDTools: Is a directory
collect2: error: ld returned 1 exit status
```

but when I change it to some different name it works.
```
$ g++ -std=c++20 JDTools/*.c JDTools/*.cpp -o jdtool
$ ./jdtool                                                                                                                  
JDTools - Patch conversion utility for Roland JD-800 / JD-990
[...]
```

Changing the `CMakeLists.txt` accordingly also worked. But I guess there might be a better option than renaming your tool.

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 9093426..8f29aec 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1,7 +1,7 @@
 cmake_minimum_required(VERSION 3.16)

 project(JDTools)
-add_executable(JDTools
+add_executable(jdtool
        JDTools/Convert800to990.cpp
        JDTools/Convert800toVST.cpp
        JDTools/Convert990to800.cpp
@@ -39,4 +39,4 @@ elseif(CMAKE_COMPILER_IS_GNUCC OR CMAKE_COMPILER_IS_GNUCXX)
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall")
 endif()

-set_property(TARGET JDTools PROPERTY CXX_STANDARD 20)
+set_property(TARGET jdtool PROPERTY CXX_STANDARD 20)
```

**Comment by sagamusix** [comment]
The correct option would be to do a shadow build, i.e. 

```
mkdir build
cd build
cmake ..
make
```

**Comment by sagamusix** [comment]
This is now documented in the readme, and the `build` folder is added to `.gitignore` so this way of building JDTools also does not leave untracked files in the repository.

**Comment by krenzlin** [comment]
Perfect, thanks alot. Seems so obvious now.
