### ISSUE TITLE
List patch parameters

### ISSUE THREAD

**Issue by acdel123** [sagamusix/JDTools#17]
Would it be possible to have an option to list patch parameter in a text format? Either for all patches in a bank or a specific patch. This is initially what I thought the existing LIST option did. I think it would be very useful to have a human readable reference of all patch parameters.

**Comment by sagamusix** [comment]
Probably doable, though it's quite a chore to gather all the parameters and print them (preferably also in a somewhat common way between JD-800/990 and the Zenology reimplementations, they store the data differently). It will probably take a while.

**Comment by sagamusix** [comment]
JDTools 0.19 has a new verb, "list-verbose", which does the same as "list" except that it also lists all the patch and setup parameters.

The new release can be found here: https://github.com/sagamusix/JDTools/releases

Let me know if there are any issues.

**Comment by acdel123** [comment]
That was incredibly fast. Thanks so much for making that change. You're a rock star!

**Comment by sagamusix** [comment]
Cheers :)
